#pragma once
const int WIDTH = 800;
const int HEIGHT = 400;

enum ID{PLAYER, ENEMY, MISC}; //IDs
enum STATE{PLAYING, PAUSED, MENU, DEFEAT, CUTSCENE}; // States
enum STAGE_VICTORY_CONDITION{HERO_HUNTING, BLOODBATH, SIEGE}; //victory conditions
enum FRACTION{DWARFKIN, GREENSKINS};
