#pragma once
const int SCREEN_WIDTH = 800;
const int WORLD_WIDTH = 1600;
const int HEIGHT = 600;
const float LANE[] = {NULL,450,470,490};

enum ID{PLAYER, ENEMY, MISC}; //IDs
enum STATE{PLAYING, PAUSED, MENU, DEFEAT, DEPLOYMENT}; // States
enum STAGE_VICTORY_CONDITION{HERO_HUNTING, BLOODBATH, SIEGE}; //victory conditions
enum FRACTION{DWARFKIN, GREENSKINS};
enum ANIMATION{WALKING, ATTACKING, DYING};
enum UNIT_TYPE{COMMON, UNCOMMON, ELITE, HERO};

